baseURL = "https://littlechin.tw"
title = "littlechin"
author = "littlechin"
copyright = "Copyright © 2022 littlechin.tw; all rights reserved."
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

[params]

  # color style
  color = 'gray'                 # linen, wheat, gray, light

  # header social icons
  github = 'littlechintw'       # github.com/YOUR_GITHUB_ID
  instagram = 'littlechintw' # instagram.com/YOUR_INSTAGRAM_ID
  rss = true
  googleAnalytics = "337941102"

  # home page profile
  avatar = 'https://www.gravatar.com/avatar/c87cbee0a4a96655bd7366b56be7a18a?s=320'
  name = '小群 | littlechin'
  bio = 'Discover new things!'

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

