# This workflow will do a clean installation of node dependencies, cache/restore them, build the 
# source code and run tests across different versions of node
# For more information see: 
# https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build Hugo

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.68.3'

      - name: Build
        run: hugo --minify
    
      - name: GH Pages deploy
        uses: Cecilapp/GitHub-Pages-deploy@3.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # A verified email.
          email: ${{ secrets.EMAIL }}
          # Where static files are.
          build_dir: docs
          branch: gh-pages
          cname: littlechin.tw