# This workflow will do a clean installation of node dependencies, cache/restore them, build the 
# source code and run tests across different versions of node
# For more information see: 
# https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build CI

on:
  push:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Install
      run: yarn
    - name: Build
      run: yarn build
      
    - name: GH Pages deploy
      uses: Cecilapp/GitHub-Pages-deploy@3.2.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        email: ${{ secrets.EMAIL }}
        build_dir: dist
        branch: gh-pages
        cname: littlechin.tw
